import = ["/home/kreejzak/.config/alacritty/rose-pine.toml"]

[font]
size = 17

[font.bold]
family = "DankMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "DankMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "DankMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "DankMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 5

[shell]
program = "/bin/zsh"

[window]
opacity = 0.95
