
[font]
size = 15

[font.bold]
family = "ComicCodeLigatures Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "ComicCodeLigatures Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "ComicCodeLigatures Nerd Font Mono"
style = "Italic"

[font.normal]
family = "ComicCodeLigatures Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = -3

[terminal.shell]
program = "/bin/zsh"

[window.padding]
x = 0
y = 0

[general]
import = ["/home/kreejzak/.config/alacritty/rose-pine.toml"]

[terminal]

[window]
opacity = 0.95
decorations = 'none'
