[colors.normal]
black = "#393A3E"
red = "#9A6C45"
green = "#817C46"
yellow = "#9E9384"
blue = "#859CA5"
magenta = "#C1C8BF"
cyan = "#DBCB88"
white = "#E4DDBB"

[colors.bright]
black = "#A09A83"
red = "#9A6C45"
green = "#817C46"
yellow = "#9E9384"
blue = "#859CA5"
magenta = "#C1C8BF"
cyan = "#DBCB88"
white = "#E4DDBB"
